version: "3.8"

services:
  app:
    build: .
    volumes:
      - cargo:/home/rust/.cargo
      - target:/home/rust/src/target
    env_file:
      - .env.docker
    ports:
      - "3030:3030"
    depends_on:
      - db
  db:
    image: postgres:alpine
    env_file:
      - .env.docker

volumes:
  cargo: {}
  target: {}
